const countries = [
    { id: 4, name: "Afghanistan", alpha2Code: "af", alpha3Code: "afg" },
    { id: 8, name: "Albania", alpha2Code: "al", alpha3Code: "alb" },
    { id: 12, name: "Algeria", alpha2Code: "dz", alpha3Code: "dza" },
    { id: 20, name: "Andorra", alpha2Code: "ad", alpha3Code: "and" },
    { id: 24, name: "Angola", alpha2Code: "ao", alpha3Code: "ago" },
    { id: 28, name: "Antigua and Barbuda", alpha2Code: "ag", alpha3Code: "atg" },
    { id: 32, name: "Argentina", alpha2Code: "ar", alpha3Code: "arg" },
    { id: 51, name: "Armenia", alpha2Code: "am", alpha3Code: "arm" },
    { id: 36, name: "Australia", alpha2Code: "au", alpha3Code: "aus" },
    { id: 40, name: "Austria", alpha2Code: "at", alpha3Code: "aut" },
    { id: 31, name: "Azerbaijan", alpha2Code: "az", alpha3Code: "aze" },
    { id: 44, name: "Bahamas", alpha2Code: "bs", alpha3Code: "bhs" },
    { id: 48, name: "Bahrain", alpha2Code: "bh", alpha3Code: "bhr" },
    { id: 50, name: "Bangladesh", alpha2Code: "bd", alpha3Code: "bgd" },
    { id: 52, name: "Barbados", alpha2Code: "bb", alpha3Code: "brb" },
    { id: 112, name: "Belarus", alpha2Code: "by", alpha3Code: "blr" },
    { id: 56, name: "Belgium", alpha2Code: "be", alpha3Code: "bel" },
    { id: 84, name: "Belize", alpha2Code: "bz", alpha3Code: "blz" },
    { id: 204, name: "Benin", alpha2Code: "bj", alpha3Code: "ben" },
    { id: 64, name: "Bhutan", alpha2Code: "bt", alpha3Code: "btn" },
    { id: 68, name: "Bolivia (Plurinational State of)", alpha2Code: "bo", alpha3Code: "bol" },
    { id: 70, name: "Bosnia and Herzegovina", alpha2Code: "ba", alpha3Code: "bih" },
    { id: 72, name: "Botswana", alpha2Code: "bw", alpha3Code: "bwa" },
    { id: 76, name: "Brazil", alpha2Code: "br", alpha3Code: "bra" },
    { id: 96, name: "Brunei Darussalam", alpha2Code: "bn", alpha3Code: "brn" },
    { id: 100, name: "Bulgaria", alpha2Code: "bg", alpha3Code: "bgr" },
    { id: 854, name: "Burkina Faso", alpha2Code: "bf", alpha3Code: "bfa" },
    { id: 108, name: "Burundi", alpha2Code: "bi", alpha3Code: "bdi" },
    { id: 132, name: "Cabo Verde", alpha2Code: "cv", alpha3Code: "cpv" },
    { id: 116, name: "Cambodia", alpha2Code: "kh", alpha3Code: "khm" },
    { id: 120, name: "Cameroon", alpha2Code: "cm", alpha3Code: "cmr" },
    { id: 124, name: "Canada", alpha2Code: "ca", alpha3Code: "can" },
    { id: 140, name: "Central African Republic", alpha2Code: "cf", alpha3Code: "caf" },
    { id: 148, name: "Chad", alpha2Code: "td", alpha3Code: "tcd" },
    { id: 152, name: "Chile", alpha2Code: "cl", alpha3Code: "chl" },
    { id: 156, name: "China", alpha2Code: "cn", alpha3Code: "chn" },
    { id: 170, name: "Colombia", alpha2Code: "co", alpha3Code: "col" },
    { id: 174, name: "Comoros", alpha2Code: "km", alpha3Code: "com" },
    { id: 178, name: "Congo", alpha2Code: "cg", alpha3Code: "cog" },
    { id: 180, name: "Congo, Democratic Republic of the", alpha2Code: "cd", alpha3Code: "cod" },
    { id: 188, name: "Costa Rica", alpha2Code: "cr", alpha3Code: "cri" },
    { id: 384, name: "Côte d'Ivoire", alpha2Code: "ci", alpha3Code: "civ" },
    { id: 191, name: "Croatia", alpha2Code: "hr", alpha3Code: "hrv" },
    { id: 192, name: "Cuba", alpha2Code: "cu", alpha3Code: "cub" },
    { id: 196, name: "Cyprus", alpha2Code: "cy", alpha3Code: "cyp" },
    { id: 203, name: "Czechia", alpha2Code: "cz", alpha3Code: "cze" },
    { id: 208, name: "Denmark", alpha2Code: "dk", alpha3Code: "dnk" },
    { id: 262, name: "Djibouti", alpha2Code: "dj", alpha3Code: "dji" },
    { id: 212, name: "Dominica", alpha2Code: "dm", alpha3Code: "dma" },
    { id: 214, name: "Dominican Republic", alpha2Code: "do", alpha3Code: "dom" },
    { id: 218, name: "Ecuador", alpha2Code: "ec", alpha3Code: "ecu" },
    { id: 818, name: "Egypt", alpha2Code: "eg", alpha3Code: "egy" },
    { id: 222, name: "El Salvador", alpha2Code: "sv", alpha3Code: "slv" },
    { id: 226, name: "Equatorial Guinea", alpha2Code: "gq", alpha3Code: "gnq" },
    { id: 232, name: "Eritrea", alpha2Code: "er", alpha3Code: "eri" },
    { id: 233, name: "Estonia", alpha2Code: "ee", alpha3Code: "est" },
    { id: 748, name: "Eswatini", alpha2Code: "sz", alpha3Code: "swz" },
    { id: 231, name: "Ethiopia", alpha2Code: "et", alpha3Code: "eth" },
    { id: 242, name: "Fiji", alpha2Code: "fj", alpha3Code: "fji" },
    { id: 246, name: "Finland", alpha2Code: "fi", alpha3Code: "fin" },
    { id: 250, name: "France", alpha2Code: "fr", alpha3Code: "fra" },
    { id: 266, name: "Gabon", alpha2Code: "ga", alpha3Code: "gab" },
    { id: 270, name: "Gambia", alpha2Code: "gm", alpha3Code: "gmb" },
    { id: 268, name: "Georgia", alpha2Code: "ge", alpha3Code: "geo" },
    { id: 276, name: "Germany", alpha2Code: "de", alpha3Code: "deu" },
    { id: 288, name: "Ghana", alpha2Code: "gh", alpha3Code: "gha" },
    { id: 300, name: "Greece", alpha2Code: "gr", alpha3Code: "grc" },
    { id: 308, name: "Grenada", alpha2Code: "gd", alpha3Code: "grd" },
    { id: 320, name: "Guatemala", alpha2Code: "gt", alpha3Code: "gtm" },
    { id: 324, name: "Guinea", alpha2Code: "gn", alpha3Code: "gin" },
    { id: 624, name: "Guinea-Bissau", alpha2Code: "gw", alpha3Code: "gnb" },
    { id: 328, name: "Guyana", alpha2Code: "gy", alpha3Code: "guy" },
    { id: 332, name: "Haiti", alpha2Code: "ht", alpha3Code: "hti" },
    { id: 340, name: "Honduras", alpha2Code: "hn", alpha3Code: "hnd" },
    { id: 348, name: "Hungary", alpha2Code: "hu", alpha3Code: "hun" },
    { id: 352, name: "Iceland", alpha2Code: "is", alpha3Code: "isl" },
    { id: 356, name: "India", alpha2Code: "in", alpha3Code: "ind" },
    { id: 360, name: "Indonesia", alpha2Code: "id", alpha3Code: "idn" },
    { id: 364, name: "Iran (Islamic Republic of)", alpha2Code: "ir", alpha3Code: "irn" },
    { id: 368, name: "Iraq", alpha2Code: "iq", alpha3Code: "irq" },
    { id: 372, name: "Ireland", alpha2Code: "ie", alpha3Code: "irl" },
    { id: 376, name: "Israel", alpha2Code: "il", alpha3Code: "isr" },
    { id: 380, name: "Italy", alpha2Code: "it", alpha3Code: "ita" },
    { id: 388, name: "Jamaica", alpha2Code: "jm", alpha3Code: "jam" },
    { id: 392, name: "Japan", alpha2Code: "jp", alpha3Code: "jpn" },
    { id: 400, name: "Jordan", alpha2Code: "jo", alpha3Code: "jor" },
    { id: 398, name: "Kazakhstan", alpha2Code: "kz", alpha3Code: "kaz" },
    { id: 404, name: "Kenya", alpha2Code: "ke", alpha3Code: "ken" },
    { id: 296, name: "Kiribati", alpha2Code: "ki", alpha3Code: "kir" },
    { id: 408, name: "Korea (Democratic People's Republic of)", alpha2Code: "kp", alpha3Code: "prk" },
    { id: 410, name: "Korea, Republic of", alpha2Code: "kr", alpha3Code: "kor" },
    { id: 414, name: "Kuwait", alpha2Code: "kw", alpha3Code: "kwt" },
    { id: 417, name: "Kyrgyzstan", alpha2Code: "kg", alpha3Code: "kgz" },
    { id: 418, name: "Lao People's Democratic Republic", alpha2Code: "la", alpha3Code: "lao" },
    { id: 428, name: "Latvia", alpha2Code: "lv", alpha3Code: "lva" },
    { id: 422, name: "Lebanon", alpha2Code: "lb", alpha3Code: "lbn" },
    { id: 426, name: "Lesotho", alpha2Code: "ls", alpha3Code: "lso" },
    { id: 430, name: "Liberia", alpha2Code: "lr", alpha3Code: "lbr" },
    { id: 434, name: "Libya", alpha2Code: "ly", alpha3Code: "lby" },
    { id: 438, name: "Liechtenstein", alpha2Code: "li", alpha3Code: "lie" },
    { id: 440, name: "Lithuania", alpha2Code: "lt", alpha3Code: "ltu" },
    { id: 442, name: "Luxembourg", alpha2Code: "lu", alpha3Code: "lux" },
    { id: 450, name: "Madagascar", alpha2Code: "mg", alpha3Code: "mdg" },
    { id: 454, name: "Malawi", alpha2Code: "mw", alpha3Code: "mwi" },
    { id: 458, name: "Malaysia", alpha2Code: "my", alpha3Code: "mys" },
    { id: 462, name: "Maldives", alpha2Code: "mv", alpha3Code: "mdv" },
    { id: 466, name: "Mali", alpha2Code: "ml", alpha3Code: "mli" },
    { id: 470, name: "Malta", alpha2Code: "mt", alpha3Code: "mlt" },
    { id: 584, name: "Marshall Islands", alpha2Code: "mh", alpha3Code: "mhl" },
    { id: 478, name: "Mauritania", alpha2Code: "mr", alpha3Code: "mrt" },
    { id: 480, name: "Mauritius", alpha2Code: "mu", alpha3Code: "mus" },
    { id: 484, name: "Mexico", alpha2Code: "mx", alpha3Code: "mex" },
    { id: 583, name: "Micronesia (Federated States of)", alpha2Code: "fm", alpha3Code: "fsm" },
    { id: 498, name: "Moldova, Republic of", alpha2Code: "md", alpha3Code: "mda" },
    { id: 492, name: "Monaco", alpha2Code: "mc", alpha3Code: "mco" },
    { id: 496, name: "Mongolia", alpha2Code: "mn", alpha3Code: "mng" },
    { id: 499, name: "Montenegro", alpha2Code: "me", alpha3Code: "mne" },
    { id: 504, name: "Morocco", alpha2Code: "ma", alpha3Code: "mar" },
    { id: 508, name: "Mozambique", alpha2Code: "mz", alpha3Code: "moz" },
    { id: 104, name: "Myanmar", alpha2Code: "mm", alpha3Code: "mmr" },
    { id: 516, name: "Namibia", alpha2Code: "na", alpha3Code: "nam" },
    { id: 520, name: "Nauru", alpha2Code: "nr", alpha3Code: "nru" },
    { id: 524, name: "Nepal", alpha2Code: "np", alpha3Code: "npl" },
    { id: 528, name: "Netherlands", alpha2Code: "nl", alpha3Code: "nld" },
    { id: 554, name: "New Zealand", alpha2Code: "nz", alpha3Code: "nzl" },
    { id: 558, name: "Nicaragua", alpha2Code: "ni", alpha3Code: "nic" },
    { id: 562, name: "Niger", alpha2Code: "ne", alpha3Code: "ner" },
    { id: 566, name: "Nigeria", alpha2Code: "ng", alpha3Code: "nga" },
    { id: 807, name: "North Macedonia", alpha2Code: "mk", alpha3Code: "mkd" },
    { id: 578, name: "Norway", alpha2Code: "no", alpha3Code: "nor" },
    { id: 512, name: "Oman", alpha2Code: "om", alpha3Code: "omn" },
    { id: 586, name: "Pakistan", alpha2Code: "pk", alpha3Code: "pak" },
    { id: 585, name: "Palau", alpha2Code: "pw", alpha3Code: "plw" },
    { id: 591, name: "Panama", alpha2Code: "pa", alpha3Code: "pan" },
    { id: 598, name: "Papua New Guinea", alpha2Code: "pg", alpha3Code: "png" },
    { id: 600, name: "Paraguay", alpha2Code: "py", alpha3Code: "pry" },
    { id: 604, name: "Peru", alpha2Code: "pe", alpha3Code: "per" },
    { id: 608, name: "Philippines", alpha2Code: "ph", alpha3Code: "phl" },
    { id: 616, name: "Poland", alpha2Code: "pl", alpha3Code: "pol" },
    { id: 620, name: "Portugal", alpha2Code: "pt", alpha3Code: "prt" },
    { id: 634, name: "Qatar", alpha2Code: "qa", alpha3Code: "qat" },
    { id: 642, name: "Romania", alpha2Code: "ro", alpha3Code: "rou" },
    { id: 643, name: "Russian Federation", alpha2Code: "ru", alpha3Code: "rus" },
    { id: 646, name: "Rwanda", alpha2Code: "rw", alpha3Code: "rwa" },
    { id: 659, name: "Saint Kitts and Nevis", alpha2Code: "kn", alpha3Code: "kna" },
    { id: 662, name: "Saint Lucia", alpha2Code: "lc", alpha3Code: "lca" },
    { id: 670, name: "Saint Vincent and the Grenadines", alpha2Code: "vc", alpha3Code: "vct" },
    { id: 882, name: "Samoa", alpha2Code: "ws", alpha3Code: "wsm" },
    { id: 674, name: "San Marino", alpha2Code: "sm", alpha3Code: "smr" },
    { id: 678, name: "Sao Tome and Principe", alpha2Code: "st", alpha3Code: "stp" },
    { id: 682, name: "Saudi Arabia", alpha2Code: "sa", alpha3Code: "sau" },
    { id: 686, name: "Senegal", alpha2Code: "sn", alpha3Code: "sen" },
    { id: 688, name: "Serbia", alpha2Code: "rs", alpha3Code: "srb" },
    { id: 690, name: "Seychelles", alpha2Code: "sc", alpha3Code: "syc" },
    { id: 694, name: "Sierra Leone", alpha2Code: "sl", alpha3Code: "sle" },
    { id: 702, name: "Singapore", alpha2Code: "sg", alpha3Code: "sgp" },
    { id: 703, name: "Slovakia", alpha2Code: "sk", alpha3Code: "svk" },
    { id: 705, name: "Slovenia", alpha2Code: "si", alpha3Code: "svn" },
    { id: 90, name: "Solomon Islands", alpha2Code: "sb", alpha3Code: "slb" },
    { id: 706, name: "Somalia", alpha2Code: "so", alpha3Code: "som" },
    { id: 710, name: "South Africa", alpha2Code: "za", alpha3Code: "zaf" },
    { id: 728, name: "South Sudan", alpha2Code: "ss", alpha3Code: "ssd" },
    { id: 724, name: "Spain", alpha2Code: "es", alpha3Code: "esp" },
    { id: 144, name: "Sri Lanka", alpha2Code: "lk", alpha3Code: "lka" },
    { id: 729, name: "Sudan", alpha2Code: "sd", alpha3Code: "sdn" },
    { id: 740, name: "Suriname", alpha2Code: "sr", alpha3Code: "sur" },
    { id: 752, name: "Sweden", alpha2Code: "se", alpha3Code: "swe" },
    { id: 756, name: "Switzerland", alpha2Code: "ch", alpha3Code: "che" },
    { id: 760, name: "Syrian Arab Republic", alpha2Code: "sy", alpha3Code: "syr" },
    { id: 762, name: "Tajikistan", alpha2Code: "tj", alpha3Code: "tjk" },
    { id: 834, name: "Tanzania, United Republic of", alpha2Code: "tz", alpha3Code: "tza" },
    { id: 764, name: "Thailand", alpha2Code: "th", alpha3Code: "tha" },
    { id: 626, name: "Timor-Leste", alpha2Code: "tl", alpha3Code: "tls" },
    { id: 768, name: "Togo", alpha2Code: "tg", alpha3Code: "tgo" },
    { id: 776, name: "Tonga", alpha2Code: "to", alpha3Code: "ton" },
    { id: 780, name: "Trinidad and Tobago", alpha2Code: "tt", alpha3Code: "tto" },
    { id: 788, name: "Tunisia", alpha2Code: "tn", alpha3Code: "tun" },
    { id: 792, name: "Turkey", alpha2Code: "tr", alpha3Code: "tur" },
    { id: 795, name: "Turkmenistan", alpha2Code: "tm", alpha3Code: "tkm" },
    { id: 798, name: "Tuvalu", alpha2Code: "tv", alpha3Code: "tuv" },
    { id: 800, name: "Uganda", alpha2Code: "ug", alpha3Code: "uga" },
    { id: 804, name: "Ukraine", alpha2Code: "ua", alpha3Code: "ukr" },
    { id: 784, name: "United Arab Emirates", alpha2Code: "ae", alpha3Code: "are" },
    { id: 826, name: "United Kingdom of Great Britain and Northern Ireland", alpha2Code: "gb", alpha3Code: "gbr" },
    { id: 840, name: "United States of America", alpha2Code: "us", alpha3Code: "usa" },
    { id: 858, name: "Uruguay", alpha2Code: "uy", alpha3Code: "ury" },
    { id: 860, name: "Uzbekistan", alpha2Code: "uz", alpha3Code: "uzb" },
    { id: 548, name: "Vanuatu", alpha2Code: "vu", alpha3Code: "vut" },
    { id: 862, name: "Venezuela (Bolivarian Republic of)", alpha2Code: "ve", alpha3Code: "ven" },
    { id: 704, name: "Viet Nam", alpha2Code: "vn", alpha3Code: "vnm" },
    { id: 887, name: "Yemen", alpha2Code: "ye", alpha3Code: "yem" },
    { id: 894, name: "Zambia", alpha2Code: "zm", alpha3Code: "zmb" },
    { id: 716, name: "Zimbabwe", alpha2Code: "zw", alpha3Code: "zwe" }]


module.exports = countries;